volumes:
  etcd:
    external: true

networks:
  etcd_area_lan:
    driver: overlay

services:
  etcd:
    image: bitnami/etcd:3
    hostname: etcd1
    environment:
      ETCD_NAME: etcd-{{.Task.Slot}}
      ETCD_ROOT_PASSWORD: ${ETCD_ROOT_PASSWORD:?ETCD_ROOT_PASSWORD is required}
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-{{.Task.Slot}}:2379
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://etcd-{{.Task.Slot}}:2380
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_INITIAL_CLUSTER_TOKEN: ${ETCD_INITIAL_CLUSTER_TOKEN:?ETCD_INITIAL_CLUSTER_TOKEN is required}
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_LOG_LEVEL: info
    volumes:
      - etcd:/bitnami/etcd/data
    ports:
      - 2379:2379
    networks:
      - etcd_area_lan
    deploy:
      replicas: ${ETCD_REPLICAS:-3}
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.role == manager
        preferences:
          - spread: node.labels.etcd
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 60s
        max_failure_ratio: 0.3
      update_config:
        parallelism: 1
        delay: 5s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
        order: stop-first
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
